
project_id = "pkmyuwlgvozgclrypdqv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = false
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54327

[functions.send-invitation-email]
verify_jwt = false

[functions.send-kakaotalk]
verify_jwt = false

[functions.receive-system-job]
verify_jwt = false
